apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: default
  labels:
    app: my-app
  annotations:
    description: "A fully detailed Pod specification"
spec:
  containers:
  - name: nginx-container
    image: nginx:1.25.2
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
      protocol: TCP
    env:
    - name: ENV_VAR_NAME
      value: "example_value"
    envFrom:
    - configMapRef:
        name: my-configmap
    - secretRef:
        name: my-secret
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20
    startupProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
    volumeMounts:
    - mountPath: /data
      name: my-volume
    lifecycle:
      preStop:
        exec:
          command: ["sh", "-c", "echo 'Cleaning up'"]
      postStart:
        exec:
          command: ["sh", "-c", "echo 'Starting up'"]
  initContainers:
  - name: init-container
    image: busybox:1.35
    command: ["sh", "-c", "echo Initializing && sleep 1"]
    volumeMounts:
    - mountPath: /init-data
      name: my-volume
  volumes:
  - name: my-volume
    emptyDir: {}
  - name: config-volume
    configMap:
      name: my-configmap
  - name: secret-volume
    secret:
      secretName: my-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  nodeSelector:
    disktype: ssd
  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/e2e-az-name
            operator: In
            values:
            - e2e-az1
            - e2e-az2
  hostNetwork: false
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  serviceAccountName: default
  priorityClassName: high-priority
  schedulerName: default-scheduler
